service: drexler-version-generator

provider:
  name: aws
  runtime: nodejs6.10

functions:
  generateNextVersion:
    handler: src/version-service.generate
    events: # endpoint triggering lambda
      - http:
          path: /version
          method: post

plugins:
  - serverless-webpack

custom:
  webpack: ./webpack.config.js
  webpackIncludeModules: true
